ALTER TABLE nodes ADD COLUMN IF NOT EXISTS postgres_installed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS postgres_version TEXT NOT NULL DEFAULT '';
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS postgres_data_initialized BOOLEAN NOT NULL DEFAULT FALSE;
