ALTER TABLE clusters ADD COLUMN IF NOT EXISTS service_location TEXT NOT NULL DEFAULT 'native';
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS service_location TEXT NOT NULL DEFAULT 'native';
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS docker_available BOOLEAN NOT NULL DEFAULT FALSE;
