import { useState } from "react";
import { usePostgresRoles, useCreatePostgresRole, useRotatePostgresRolePassword, useDeletePostgresRole, type PostgresRole } from "~/hooks/usePostgresRoles";
import { Card, CardHeader, CardTitle, CardContent } from "~/components/ui/card";
import { Button } from "~/components/ui/button";
import {
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell,
} from "~/components/ui/table";
import { Key } from "lucide-react";
import { FeatureNote, ConnectionRow, RoleStatusBadge, CopyButton, connectionURI } from "./ClusterHelpers";
import { PageSpinner } from "~/components/Spinner";

interface ManagedRolesCardProps {
  clusterId: string;
  host: string;
  port: number;
  sslMode: string;
  revealed: { role: PostgresRole; password: string } | null;
  onReveal: (value: { role: PostgresRole; password: string }) => void;
  onDismissReveal: () => void;
}

export function ManagedRolesCard({
  clusterId,
  host,
  port,
  sslMode,
  revealed,
  onReveal,
  onDismissReveal,
}: ManagedRolesCardProps) {
  const { data, isLoading } = usePostgresRoles(clusterId);
  const createRole = useCreatePostgresRole();
  const rotatePassword = useRotatePostgresRolePassword(clusterId);
  const deleteRole = useDeletePostgresRole(clusterId);
  const [roleName, setRoleName] = useState("");
  const [roleKind, setRoleKind] = useState("read_write");
  const [error, setError] = useState<string | null>(null);

  const roles = data?.roles ?? [];

  function handleCreate() {
    setError(null);
    createRole.mutate(
      { clusterId, roleName: roleName.trim(), roleKind },
      {
        onSuccess: (res) => {
          setRoleName("");
          onReveal({ role: res.role, password: res.oneTimePassword });
        },
        onError: (err) => setError(err instanceof Error ? err.message : "Failed to create role"),
      },
    );
  }

  function handleRotate(role: PostgresRole) {
    setError(null);
    rotatePassword.mutate(role.id, {
      onSuccess: (res) => onReveal({ role: res.role, password: res.oneTimePassword }),
      onError: (err) => setError(err instanceof Error ? err.message : "Failed to rotate password"),
    });
  }

  function handleDelete(role: PostgresRole) {
    setError(null);
    if (!window.confirm(`Drop PostgreSQL role ${role.roleName}? This cannot be undone.`)) return;
    deleteRole.mutate(role.id, {
      onError: (err) => setError(err instanceof Error ? err.message : "Failed to delete role"),
    });
  }

  const canSubmit = roleName.trim().length > 0 && !createRole.isPending;

  return (
    <Card className="shadow-xs">
      <CardHeader className="border-b border-border/60 pb-4">
        <CardTitle className="text-sm font-semibold tracking-tight text-foreground flex items-center gap-2">
          <Key className="size-4 text-muted-foreground" />
          Managed Roles
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-5 pt-6">
        <FeatureNote title="What this does:">
          A role is a database login. Create one role per app or person so access can be rotated or removed without sharing the main PostgreSQL admin password.
        </FeatureNote>
        <p className="text-xs text-muted-foreground">
          Create application users safely. Passwords are generated by Skylex and shown only once after create or rotate.
        </p>

        {revealed && (
          <div className="rounded-lg border border-emerald-200/50 bg-emerald-50/50 p-4 dark:border-emerald-800/50 dark:bg-emerald-950/20">
            <div className="flex items-start justify-between gap-3">
              <div className="min-w-0 flex-1 space-y-2">
                <p className="text-xs font-semibold uppercase tracking-wider text-emerald-800 dark:text-emerald-300">
                  One-time password generated for {revealed.role.roleName}
                </p>
                <ConnectionRow label="Password" value={revealed.password} />
                {host && <ConnectionRow label="Connection URI" value={connectionURI(host, port, revealed.role.roleName, sslMode, revealed.password)} />}
                <p className="text-[10px] font-semibold text-emerald-700 dark:text-emerald-400">
                  Save this password now. Skylex will not show it again.
                </p>
              </div>
              <Button
                variant="outline"
                size="xs"
                onClick={onDismissReveal}
                className="shrink-0 text-emerald-800 border-emerald-300/50 hover:bg-emerald-100/50 dark:text-emerald-300 dark:border-emerald-800 dark:hover:bg-emerald-900/30"
              >
                Dismiss
              </Button>
            </div>
          </div>
        )}

        <div className="rounded-lg border border-border p-4 bg-muted/10">
          <div className="grid grid-cols-1 gap-3 md:grid-cols-[1fr_12rem_auto] md:items-end">
            <div className="space-y-1.5">
              <label className="block text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Role Name</label>
              <input
                type="text"
                value={roleName}
                onChange={(e) => setRoleName(e.target.value)}
                placeholder="app_user"
                className="w-full px-3 py-1.5 text-sm border rounded-md bg-transparent border-input text-foreground transition-all focus:outline-none focus:ring-1 focus:ring-ring disabled:opacity-50"
              />
            </div>
            <div className="space-y-1.5">
              <label className="block text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Role Kind</label>
              <select
                value={roleKind}
                onChange={(e) => setRoleKind(e.target.value)}
                className="w-full px-3 py-1.5 text-sm border rounded-md bg-transparent border-input text-foreground transition-all focus:outline-none focus:ring-1 focus:ring-ring disabled:opacity-50"
              >
                <option value="read_write" className="bg-popover text-popover-foreground">Read/Write</option>
                <option value="read_only" className="bg-popover text-popover-foreground">Read Only</option>
                <option value="admin" className="bg-popover text-popover-foreground">Admin</option>
                <option value="custom" className="bg-popover text-popover-foreground">Custom</option>
              </select>
            </div>
            <Button
              onClick={handleCreate}
              disabled={!canSubmit}
              size="sm"
            >
              {createRole.isPending ? "Creating..." : "Create Role"}
            </Button>
          </div>
          {error && <p className="mt-3 text-xs font-semibold text-destructive">{error}</p>}
        </div>

        {isLoading ? (
          <PageSpinner />
        ) : roles.length === 0 ? (
          <div className="py-8 text-center border border-dashed rounded-lg border-border/80">
            <p className="text-xs text-muted-foreground">
              No managed roles yet.
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto rounded-lg border border-border">
            <Table>
              <TableHeader>
                <TableRow className="bg-muted/30">
                  <TableHead className="h-9 text-xs font-semibold uppercase tracking-wider text-muted-foreground px-4">Role</TableHead>
                  <TableHead className="h-9 text-xs font-semibold uppercase tracking-wider text-muted-foreground px-4">Kind</TableHead>
                  <TableHead className="h-9 text-xs font-semibold uppercase tracking-wider text-muted-foreground px-4">Status</TableHead>
                  <TableHead className="h-9 text-xs font-semibold uppercase tracking-wider text-muted-foreground px-4">Connection URI</TableHead>
                  <TableHead className="h-9 text-xs font-semibold uppercase tracking-wider text-muted-foreground px-4 text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {roles.map((role) => (
                  <TableRow key={role.id} className="hover:bg-muted/10 border-b border-border/40 last:border-none">
                    <TableCell className="px-4 py-2.5 font-semibold text-foreground">{role.roleName}</TableCell>
                    <TableCell className="px-4 py-2.5 text-foreground/80 text-xs">{role.roleKind.replace("_", " ")}</TableCell>
                    <TableCell className="px-4 py-2.5"><RoleStatusBadge status={role.status} /></TableCell>
                    <TableCell className="px-4 py-2.5">
                      {host ? (
                        <div className="flex items-center gap-1.5">
                          <code className="max-w-[28rem] truncate text-xs text-muted-foreground font-mono bg-muted/40 px-1.5 py-0.5 rounded border border-border/40">
                            {connectionURI(host, port, role.roleName, sslMode)}
                          </code>
                          <CopyButton text={connectionURI(host, port, role.roleName, sslMode)} />
                        </div>
                      ) : (
                        <span className="text-xs text-muted-foreground">Endpoint unavailable</span>
                      )}
                    </TableCell>
                    <TableCell className="px-4 py-2.5 text-right">
                      <div className="flex justify-end gap-1">
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleRotate(role)}
                          disabled={role.status === "deleting" || rotatePassword.isPending}
                          className="text-amber-600 hover:text-amber-700 hover:bg-amber-50 dark:hover:bg-amber-950/20 text-xs font-medium h-7 px-2"
                        >
                          Rotate
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleDelete(role)}
                          disabled={role.status === "deleting" || deleteRole.isPending}
                          className="text-destructive hover:text-destructive hover:bg-destructive/10 text-xs font-medium h-7 px-2"
                        >
                          Delete
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
